create table route (
    id bigint generated by default as identity,
    description varchar(255),
    name varchar(255),
    path TEXT,
    primary key (id)
);

create table users (
    id bigint generated by default as identity,
    password varchar(255),
    username varchar(255) unique,
    primary key (id)
);