spring.application.name=OutdoorLoop

spring.datasource.url=jdbc:postgresql://postgres:5432/outdoorloop
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# temporary
spring.security.user.name=admin
spring.security.user.password=admin